name: Deploy to web server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy code
      uses: appleboy/scp-action@master
        with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        passphrase: 
        rm: true
        source: "/"
        target: "${{ secrets.SSH_SITE_PATH }}"