name: Push to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      - name: Push to server
        run: |
          ssh $oleksii@$hutnichenko.dev << EOF
          cd /var/www/hutnichenko.dev/html/
          git pull origin main
          EOF
