name: Push to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y rsync
      
    - name: Deploy code
      run: rsync -avz --delete --exclude='.git/' ${{ github.workspace }}/* oleksii@3.125.106.223:/var/www/hutnichenko.dev/html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
