name: Deploy to web server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.SSH_SITE_PATH }}
          git stash
          git pull
          git stash apply
<<<<<<< HEAD
          sudo systemctl restart nginx
=======
          sudo systemctl restart nginx
>>>>>>> b9d7d8b33dcba0ca1475862a1c44eee1abc7ffa8
