name: Push to Server

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to web server
      run: |
        # Replace with your deployment script
        ssh oleksii@hutnichenko.dev "cd /var/www/hutnichenko.dev/html/ && git pull"
